language: php

## Versions to test
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

## Use lowest stable versions for oldest version test
matrix:
  include:
    - php: 7.1
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

## Cache composer
cache:
  directories:
  - $HOME/.composer/cache

## Run composer update
before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

## Run tests (codesniffer and PhpUnit)
script:
  - vendor/bin/phpcs --standard=psr12 src/
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

## Report code coverage to scrutinizer
after_script:
  wget https://scrutinizer-ci.com/ocular.phar
  php ocular.phar code-coverage:upload --format=php-clover coverage.clover